### ISSUE TITLE
Possible memory leakage

### ISSUE THREAD

**Issue by AndreasMartin72** [kyamagu/mexplus#10]
Thank you for this great tool. It simplifies all interactions on mxArray's!
In the MATLAB documentation for mxSetField and mxSetCell, there is the advise to firstly free memory allocated by elements beeing displaced:
http://de.mathworks.com/help/matlab/apiref/mxsetcell.html
http://de.mathworks.com/help/matlab/apiref/mxsetfield.html
(Anyhow there is a hint in mxDestroyArray to do not ;-) I think it's meant not to leave fields or cells unset)

The reason why there might be no "real" memory leakage is due to MATLAB memory management, cleaning up, when a MEX function returns:
http://de.mathworks.com/help/matlab/matlab_external/memory-management.html

For "clean code" there should be a note about it, or a freeing function.
What do you think  about?

Cheers, Andreas

**Comment by kyamagu** [comment]
@AndreasMartin72 You're right, thanks for the PR!
