### ISSUE TITLE
Not able to set a cell with mxArray*

### ISSUE THREAD

**Issue by AndreasMartin72** [kyamagu/mexplus#15]
I currently try to set a cell item by another mxArray* item:
```
MxArray data( MxArray::Numeric<double>( 10, 20 ) );
MxArray cells( MxArray::Cell( 3, 3 ) );
cells.set( 0, 0, data.release() ); // cells.set( 0, data.release() ) don't too
```

Is there a proper way to do this?

Regards, Andreas

**Comment by kyamagu** [comment]
@AndreasMartin72 Seems `cells.set(0, data.release())` works with gcc 4.8.4 on Ubuntu 14.04 + Matlab R2014a. At least this compiler can correctly identify the method signature:

    MxArray::void set(mwIndex index, mxArray* value)

The other signature (row-column index) is not included in the current `MxArray` definition. Perhaps this has to be implemented...
