### ISSUE TITLE
auto_ptr is not available anymore in VS2017.3

### ISSUE THREAD

**Issue by patrikhuber** [kyamagu/mexplus#23]
Hi!

`std::auto_ptr` is not available anymore in VS2017.3, it has been deprecated in the ISO C++ standard and MS removed it. It might be an easy fix and can just be replaced with `std::unique_ptr`. I'm sorry I currently don't have time to do a PR, but I still wanted to report it - maybe you've got time for it, otherwise I might get to it over the next couple of months :-)

**Comment by kyamagu** [comment]
@patrikhuber This should be an easy fix. Let's check if simple replacement to `unique_ptr` works.

**Comment by kyamagu** [comment]
@patrikhuber Should be fixed now. Perhaps there should be AppVeyor CI for windows build test in the future.

**Comment by patrikhuber** [comment]
Cool, thank you! Simple enough indeed. I just tried it and the error went away and there's no new one, so it seems fine! I can't fully test currently because there's some other errors now which will take me a while to fix (but they're in my code, not this PR).

Thanks!
