### ISSUE TITLE
Define MEX function as a MATLAB class method

### ISSUE THREAD

**Issue by hokiedsp** [kyamagu/mexplus#29]
Hey, pretty cool C++ wrapping of mxXXX functions.

This really doesn't affect your code per se, just a comment on your ReadMe example.

FYI, it would be more foolproof if you define MEX interface function as a private/protected method of the wrapping class. I think it's a little known secret that you can do this. Check out my hokiedsp/matlab-mexutils repo for an example.

**Comment by kyamagu** [comment]
@hokiedsp Thanks, the recommendation here is to use `private/` directory to hide MEX interface: https://github.com/kyamagu/mexplus#dispatching-calls

**Comment by hokiedsp** [comment]
Hum, I missed that part of the documentation and yeah I guess private folder makes sense, too. For some reason, I thought MATLAB doesn’t acknowledge a private folder inside an @class folder but I guess I’m wrong.
