### ISSUE TITLE
Conversion of vector<CustomType> fails with 'assign' error

### ISSUE THREAD

**Issue by patrikhuber** [kyamagu/mexplus#30]
Hi!

I'm trying to improve my mexplus bindings for `Eigen`. One thing I need to do is pass a `std::vector<Eigen::MatrixXd>` to and from Matlab. [My bindings](https://github.com/patrikhuber/eos/blob/7f0e46179112c44c26321491ea0246394a9a5a8a/matlab/include/mexplus_eigen.hpp#L40-L106) work fine for passing a single `Eigen::MatrixXd` but when I try to pass an `std::vector<Eigen::MatrixXd>`, I get the following compile errors:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'assign': is not a member of 'Eigen::Matrix<double,-1,-1,0,-1,-1>'	eos-matlab-test	eos\3rdparty\mexplus\include\mexplus\mxarray.h	988	
(on this line: `value->assign(data_pointer, data_pointer + array_size);`)

> Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'assign': is not a member of 'Eigen::Matrix<double,-1,-1,0,-1,-1>'	eos-matlab-test	eos\3rdparty\mexplus\include\mexplus\mxarray.h	1035	
(on this line: `value->assign(data_pointer, data_pointer + mxGetNumberOfElements(array));`)

I think I could probably write to/from functions for `std::vector<Eigen::MatrixXd>` to make this error disappear, and then these more specialised functions would get called. But is that a good idea? Since individual to/from functions for both `std::vector` as well as `Eigen::MatrixXd` exist, shouldn't that work and be better?

Actually, according to the readme, this should work:

> // Then you can use any of the following.
std::vector<MyObject> object_vector;
MxArray::to<std::vector<MyObject> >(prhs[1], &object_vector);

but that results in the same compile errors.

Also maybe if you allow me an additional, a bit broader question: Would you advise to write the Eigen bindings in this way? Or do you have any better design suggestions? (apart from the suggestions you already gave me last year in #14, thank you very much again for that!)

Thank you very much for any help!

**Comment by kyamagu** [comment]
@patrikhuber I am not familiar with Eigen library, but my bet is that `Eigen::MatrixXd` itself is a template and that might be treating `Eigen::MatrixXd` as a container just like a `std::vector`. The exact check is happening [here](https://github.com/kyamagu/mexplus/blob/49457dc4db07cfee279fee550a22b6213c984803/include/mexplus/mxarray.h#L1001)

For a quick workaround for this issue, you can specialize `std::vector<Eigen::MatrixXd>`.

To make conversion more efficient, you can instantiate numeric matrix first and use `std::copy` or ANSI C `memcpy` to copy data, assuming everything is column-major order.
https://github.com/patrikhuber/eos/blob/7f0e46179112c44c26321491ea0246394a9a5a8a/matlab/include/mexplus_eigen.hpp#L48

**Comment by patrikhuber** [comment]
> I am not familiar with Eigen library, but my bet is that Eigen::MatrixXd itself is a template and that might be treating Eigen::MatrixXd as a container just like a std::vector. The exact check is happening here

Yes, it is a template indeed. Aah! So the check, if I understand correctly, thinks that `Eigen::MatrixXd` is a `std::vector`, because it has a first template parameter (and it's a `double`), so the check here fires: https://github.com/kyamagu/mexplus/blob/49457dc4db07cfee279fee550a22b6213c984803/include/mexplus/mxtypes.h#L309-L311
And then obviously it fails because it tries to call `std::vector::assign(...)`.
Is that correct?

Do you think we could do a better solution than the "specialise std::vector<Eigen::MatrixXd>" workaround?

**Comment by kyamagu** [comment]
@patrikhuber For now, I recommend `std::vector<Eigen::MatrixXd>` specialization. The desired solution is a fix for a better template support (c.f., #25 ), but that requires major API updates.

**Comment by patrikhuber** [comment]
@kyamagu Ok, I will! I'll close this then in favour of #25.
Thank you very much for the quick replies! :-)
