### ISSUE TITLE
Fusing mexplus with mexopencv

### ISSUE THREAD

**Issue by jbriales** [kyamagu/mexplus#7]
I need to use cv::Mat objects, for example, and I suppose it can be also done defining new ::from and ::to methods in MxArray. However, I would like to know if there is any way I could directly use the mexopencv wrapper to use opencv objects from mexplus too.

**Comment by patrikhuber** [comment]
@jbriales, would you be willing to share your file with the `cv::Mat` `::from` and `::to` methods for mexplus?
Thanks!

**Comment by jbriales** [comment]
Hi @patrikhuber it's been a while since I last used this package, but I will try to find it when a get a spare moment and commit it!

**Comment by patrikhuber** [comment]
@jbriales Thank you, much appreciated!
